name: Flutter Android ABI Split Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Run tests
        run: flutter test
      
      - name: Build split ABI APKs
        run: flutter build apk --split-per-abi --release
        # 生成针对不同CPU架构的APK（armeabi-v7a、arm64-v8a、x86_64）
      
      - name: Upload split APKs
        uses: actions/upload-artifact@v3
        with:
          name: split-abi-apks
          path: build/app/outputs/flutter-apk/*.apk
          # 上传所有生成的ABI拆分APK
